# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg)
  interp_config = dbg
  object_config = dbg
  stack_config = dbg
  concat_config = dbg
  test_config = dbg
  fnv_config = dbg
  clobber_config = dbg
endif
ifeq ($(config),dist)
  interp_config = dist
  object_config = dist
  stack_config = dist
  concat_config = dist
  test_config = dist
  fnv_config = dist
  clobber_config = dist
endif

PROJECTS := interp object stack concat test fnv clobber

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

interp: fnv object stack
ifneq (,$(interp_config))
	@echo "==== Building interp ($(interp_config)) ===="
	@${MAKE} --no-print-directory -C . -f interp.make config=$(interp_config)
endif

object:
ifneq (,$(object_config))
	@echo "==== Building object ($(object_config)) ===="
	@${MAKE} --no-print-directory -C . -f object.make config=$(object_config)
endif

stack:
ifneq (,$(stack_config))
	@echo "==== Building stack ($(stack_config)) ===="
	@${MAKE} --no-print-directory -C . -f stack.make config=$(stack_config)
endif

concat: object stack fnv
ifneq (,$(concat_config))
	@echo "==== Building concat ($(concat_config)) ===="
	@${MAKE} --no-print-directory -C . -f concat.make config=$(concat_config)
endif

test: stack fnv
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make config=$(test_config)
endif

fnv:
ifneq (,$(fnv_config))
	@echo "==== Building fnv ($(fnv_config)) ===="
	@${MAKE} --no-print-directory -C . -f fnv.make config=$(fnv_config)
endif

clobber:
ifneq (,$(clobber_config))
	@echo "==== Building clobber ($(clobber_config)) ===="
	@${MAKE} --no-print-directory -C . -f clobber.make config=$(clobber_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f interp.make clean
	@${MAKE} --no-print-directory -C . -f object.make clean
	@${MAKE} --no-print-directory -C . -f stack.make clean
	@${MAKE} --no-print-directory -C . -f concat.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean
	@${MAKE} --no-print-directory -C . -f fnv.make clean
	@${MAKE} --no-print-directory -C . -f clobber.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   interp"
	@echo "   object"
	@echo "   stack"
	@echo "   concat"
	@echo "   test"
	@echo "   fnv"
	@echo "   clobber"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"